[default]
extend-ignore-re = [
    # Latex formula
    "\\$.+?\\$",
]

[default.extend-words]
als = "als"
ist = "ist"
tocken = "tocken"

[files]
extend-exclude = ["assets/**/*", "tests/sqllogictest/*.slt"]
